### ISSUE TITLE
Filename issues with custom components

### ISSUE THREAD

**Issue by anku94** [EliEladElrom/cra-template-must-have-libraries#1]
Hi,

While trying to use a custom component using:

`npx generate-react-cli component HelloD3 --type=d3`

The generated component tree looks like this:

```
HelloD3
├── component.tsx
├── style.scss
└── test.tsx
```

These names should apparently be `HelloD3.[tsx|scss]` for the rest of the code to work. I think this might be an issue with `generate-react-cli` but I'm not sure if this can be handled with the config. The documentation does describe a `TemplateName` special keyword, but it seems to apply to the component type (`d3`), and not hte component name (`HelloD3`).

**Comment by EliEladElrom** [comment]
Hi @anku94 -- what you doing is correct.  It looks like an update to filenames in generate-react-cli due to a recent release is causing this issue. I just published a new commit and you are good to go, give it a try now.
