### ISSUE TITLE
Installation fails at node-sass

### ISSUE THREAD

**Issue by rebuilt** [EliEladElrom/cra-template-must-have-libraries#6]
Hello, thanks for your project.  I'm trying to follow the steps in this book: https://www.apress.com/gp/book/9781484270516

The installer fails at the node-sass step.
There's a lot of information printed but I think the important bit is 
```bash
error /home/{usr}/workspace/javascript/react/integratingd3withreact/your-project-name/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
```
[error.txt](https://github.com/EliEladElrom/cra-template-must-have-libraries/files/7146393/error.txt)

```
❯ yarn -v
1.22.11
```

`yarn add node-sass` completes without error.  I'm not sure what I should try.

**Comment by HelpMe-Pls** [comment]
@EliEladElrom I'm having the same issue after executing the command `yarn create react-app starter-project --template must-have-libraries`, which might involves the version of node-sass that isn't compatible with my NodeJS version as per this link from StackOverFlow: https://stackoverflow.com/questions/60394291/error-node-modules-node-sass-command-failed

My `node -v` returns `16.9.1` which is the latest current version, while your `node-sass` version defined in the dependencies is `4.14.1`
![image](https://user-images.githubusercontent.com/43715386/134373662-ea3864d0-5f23-4452-ae0f-90f1e7401bbd.png)
 
My solution is to update the `node-sass` version to `>=4.14.1`, which seems to work just fine after i run `yarn` to install the deps on a clone version of this repo. Correct me if i'm wrong, and i also opened a PR on this, please have a look. Thank you.

**Comment by EliEladElrom** [comment]
Hey @HelpMe-Pls thanks for the comment and finding out the issue and solution.  It's better to specify exact version, what version of `node-saas` you using, is the latest version works?

**Comment by HelpMe-Pls** [comment]
@EliEladElrom, thank you for the suggest of exact version. I tried deleting `node_modules` and `yarn.lock` then specifying the latest version by running `yarn add node-sass@6.0.1`. The output is exactly the same as my previous comment (of which i'm unable to find a solution). My current `node-sass` version (at global scope i believe) is also `6.0.1`: 
![image](https://user-images.githubusercontent.com/43715386/134554016-715f0ff9-2c90-4103-a364-141c558928b5.png)

What i did above was trying to use the latest compatible versions of `NodeJS` and `node-sass` following their document, but for some vague reasons, the pair doesn't work. So i tried the LTS version of NodeJS which seems to be a compatible match with the `4.14.1` version that you specified (according to https://www.npmjs.com/package/node-sass), by running the commands: `nvm install v14.17.6` and `nvm use 14.17.6`, deleting `node_modules` and `yarn.lock` once again then run `yarn` and `yarn start`, works just fine, problem solved 💯 
![image](https://user-images.githubusercontent.com/43715386/134559268-92b38556-4dcd-475a-a867-ff8ebc6f1351.png)

It just seems like `node-sass` prefer to work with the LTS version of NodeJS, i don't know why it doesn't work with the latest current version. It is what it is, @rebuilt, i hope you try out my possible solution for this issue and see if it solves the problem, for now...

**Comment by EliEladElrom** [comment]
Hey @HelpMe-Pls this is typical issue with nodejs/npm and other libraries. For that reason I also set this project on docker if you familiar so you don't need to deal with envs;
`$ docker run -p 8080:80 elieladelrom/cra-template-must-have-libraries` thanks for putting this out here, I hope it will be useful for others.
